### PR TITLE
Show module load errors with atom notifications

### PR DESCRIPTION
**Pull request by dgendill**
I recently updated to 0.11.5 from 0.11.4 and I couldn't figure out why ide-purescript wasn't working.  In the console I was first seeing a log saying:

```
[Error] Version mismatch for the externs at:
/home/dom/project/output/RC.Units/externs.json Expected: 0.11.5 Found: 0.11.4."
```
So I deleted the output folder, and then I was seeing this error in the console:

```
"Your output directory didn't exist. This usually means you didn't compile your
project yet. psc-ide needs you to compile your project (for example by running
pulp build) Left /home/dom/project/output/: getDirectoryContents:openDirStream:
does not exist (No such file or directory)"
```

So I went into Main.purs and added a call to `raiseError` when module loading errors show up and now it will show the errors like this...

image

But it looks like the error notification disappears pretty quickly afterwords, so the user wouldn't be able to inspect the message.  I was wondering if it's possible to show the error in a box that requires the user to click dismiss/close all.  Do you know of a function that can do that?  Also, any thoughts on this - is there a better way to notify the user of these types of errors?

### CODE REVIEW

**Comment by nwolverson** [comment]
The one concern about adding error popups is that when things are broken people end up with flying errors everywhere. Looks like this is just added on server start so shouldn't be too bad, though I think it is in the retry section so may popup multiple errors on slow server start?

I think the notifications API supports more persistent ones with buttons but I'd tend to suggest holding off on that unless it's a known error with some resolution possible

**Comment by dgendill** [comment]
Yeah, I agree the long string of notification errors are problematic.  I'll try out my change for a few days and see how it works in different situations.  Maybe I'll dig deeper into psc-ide and the other into the code too. Ideally, we could separate out the non-important errors from the ones that user can act on, and only show the ones that are helpful.

**Comment by nwolverson** [comment]
Yeah, there are a couple of issues, one is that I just throw errors in Aff rather than passing around as values, and the other is that errors in psc-ide are just strings just now anyway, potentially if we had some sort of error code etc there would be a nice way of making different decisions on handling particular errors.

Happy to merge this in regardless as it can always be tweaked, I'll do so once I get to a machine and give a quick try out

**Comment by nwolverson** [comment]
Merged 06c3145cf6a3817c9ed08f9b5338be3ab2b10839

**Pull request closed without merging**
