### PR TITLE
Add support for calling `spago sources` to get source locations.

### PR DESCRIPTION
**Pull request by Dretch**
This depends upon having the latest purescript-language-server added
to the package set.

This goes with https://github.com/nwolverson/purescript-language-server/pull/50

### CODE REVIEW

**Comment by nwolverson** [comment]
Not sure what you mean "This depends upon having the latest purescript-language-server added
to the package set." - I think this just requires a new version of the language server executable itself? This corresponds to bumping a npm dependency once that is published - the confusion being, there is also a source dependency in the PureScript world separate from the npm dependency.

(Hope that's clear as mud)

**Comment by nwolverson** [comment]
Looks like this project needs some work to get to build with current stuff, it looks like you did indeed build there - what package set/compiler were you building against?

**Comment by Dretch** [comment]
> Not sure what you mean "This depends upon having the latest purescript-language-server added
to the package set." - I think this just requires a new version of the language server executable itself? This corresponds to bumping a npm dependency once that is published - the confusion being, there is also a source dependency in the PureScript world separate from the npm dependency.

Yeah, you understand perfectly. Sorry for the confusion.

> Looks like this project needs some work to get to build with current stuff, it looks like you did indeed build there - what package set/compiler were you building against?

As you say, it doesn't build with Purescript 0.12, so I used 0.11.7

Also, I noticed you published a new version of the vscode plugin with the spago sources flag config - thanks!

**Comment by Dretch** [comment]
Hi @nwolverson , any chance of a new release with this code in? Pretty please :heart: (I am also happy to help out if you want contributions for something).

**Pull request merged**
